### ISSUE TITLE
Fix `tail` strategy on row limits when no file limits are added

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#2653]
@ericpgreen2 reported this.
When we specify following strategy :
```
type: "gcs"
uri: "gs://pkg.rilldata.com/example-github-analytics/duckdb/duckdb/commit_details/*commit_details.parquet"
extract:
  rows:
    strategy: tail
    size: 50MB
```

Currently we look at the first files which match the glob pattern and download last 50MB data from those files. 
However the user expectation would generally be to fetch last 50MB data.
