### ISSUE TITLE
Uniform Y-axes for pivots

### ISSUE THREAD

**Issue by kmatt** [rilldata/rill#2960]
_Rill Developer v0.32_

When using an SQL PIVOT in DuckDB, we often want to compare the resulting measure columns to each other. Pivots are common because data often ends up in Excel, and would prefer pivoting in SQL vs Excel pivot tables.

```
WITH scores AS (
    SELECT sample_id,
        date_trunc('hour', sample_time) as hh,
        score
    FROM read_json_auto('/path/to/data/*.json')
)
PIVOT scores ON score in (1,2,3,4,5)
USING count(sample_id)
GROUP BY hh
```

**Is your feature request related to a problem? Please describe.**
When rendering a PIVOT query, each measure's Y-axis is scaled independently.

**Describe the solution you'd like**
Setting a Y-axis max() in the metric definition based on a column value (MAX of all metrics) would make visual comparison easier.

**Describe alternatives you've considered**
Percentages, but these do not render with a uniform 0 - 1 (0% - 100%) Y-axis:

![image](https://github.com/rilldata/rill/assets/435936/6a7ff792-7d3e-407c-87e4-c216161d22bf)

**Additional context**
In this example, rendering the charts as bars would also improve comparisons.

### Is this the right way to render an SQL PIVOT?

```
timeseries: "hh"
smallest_time_grain: hour
measures:
  - label: 5
    expression: sum("5")
    name: Score5
    format_preset: humanize
    valid_percent_of_total: true
  - label: 4
    expression: sum("4")
    name: Score4
    format_preset: humanize
    valid_percent_of_total: true
  - label: 3
    expression: sum("3")
    name: Score3
    format_preset: humanize
    valid_percent_of_total: true
  - label: 2
    expression: sum("2")
    name: Score2
    format_preset: humanize
    valid_percent_of_total: true
  - label: 1
    expression: sum("1")
    name: Score1
    format_preset: humanize
    valid_percent_of_total: true
dimensions:
  - name: hh
    label: Hour
    column: hh
    description: "Hour of day"
```
