### ISSUE TITLE
Application is sluggish on Safari

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3257]
Rill Developer is very sluggish on Safari ([Slack report](https://rilldata.slack.com/archives/C0415QK8DK6/p1689750710455449)).

Safari's profiling tools reveal that at least two culprits are animations and tooltips.

**Comment by ericpgreen2** [comment]
To start, we can experiment by turning off all animations for Safari users.

Here's some CSS:
```css
.no-animation * {
  animation-duration: 0s !important;
  transition-duration: 0s !important;
}
```

Here are some docs worth reading about browser detection: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
