### ISSUE TITLE
Document project-level resource configuration

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3544]
We're missing documentation for project-level resource configuration. One use case is a refresh policy across all sources:
```yaml
# rill.yaml
sources:
  refresh:
    cron: ...
```
