### ISSUE TITLE
Feat: Treating Nulls as Zero

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3573]
We should consider adding a `treat_nulls_as_zero` property on dashboard measures (that defaults to false). For example:
```
measures:
    - label: Average Measure
      name: avg_measure
      expression: avg(X)
      description: 
      format_preset: humanize
      treat_nulls_as_zero: true
```
In the majority of cases, we will want to treat these as nulls as this is the preferred behavior for many end users. However, there are other use cases where the end user will want to treat this as zero for very specific or contextual reasons ([example](https://rilldata.slack.com/archives/C04UY5NTXA9/p1701209544997049?thread_ts=1701206417.036689&cid=C04UY5NTXA9)). _(If difficult to implement at the dashboard measure level, we could perhaps make it a dashboard level property as well)_
