### ISSUE TITLE
Globbing in S3 doesn't work

### ISSUE THREAD

**Issue by janjagusch** [rilldata/rill#3701]
**Describe the bug**

Using globbing in my source.yaml doesn't work.

```yaml
type: s3
endpoint: https://myendpoint.example
uri: s3://mybucket/**/*.parquet
```

Returns the following error in the Rill frontend:

```
Invalid path. Please check your path.
```

What's interesting is that Rill can list the objects in the glob. It's just not able to retrieve them. From the backend logs:

```
2023-12-14T11:41:22.047 ERROR   Reconcile failed
{
  "name": "example",
  "kind": "Source",
  "elapsed": "74ms",
  "error": "failed to ingest source: Object(\"mypath/myhivekey%3D1/myuuid.parquet\"
  NewReader: blob (key \"mypath/myhivekey%3D1/myuuid.parquet\") (code=NotFound):
  NoSuchKey: The specified key does not exist\n\tstatus code: 404, request id:
  bf413c3c-5658-4a46-928f-44bdf1d9a7a1, host id: RqF22fMg42"
}
```

Fetching the file from the error log without globbing works.

```yaml
type: s3
endpoint: https://myendpoint.example
uri: s3://mybucket/mypath/myhivekey=1/myuuid.parquet
```
Fetching the data via globbing through the DuckDB CLI also works:

```SQL
SELECT * FROM 's3://mybucket/**/*.parquet';
```

So, this seems to be related to how Rill implements globbing.

**To Reproduce**
I'm running this inside corporate infrastructure on a custom object store (Apache Ozone), so currently it's hard to reproduce. I can try to make reproducing this more straightforward, if necessary.

**Expected behavior**
I expect rill to correctly process the globbing in my URI and return all matching data.

**Desktop (please complete the following information):**
- OS: Linux (Rill Container Image)
 - Browser: Edge
 - Version: 0.37.2 – f6060729
