### ISSUE TITLE
Dashboard: When a dashboard has 0 measures/dimensions, show a CTA

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3834]
**Describe the bug**
With the "View As" feature, it's possible that a user will see a blank dashboard. For example, with this access policy...

```yaml
security:
  access: "{{ .user.admin }} OR '{{ .user.domain }}' == 'rilldata.com'"
  include:
    - if: "{{ .user.admin }}"
      names: 
        - total_records
```

... any non-admin user with the `rilldata.com` domain will see a dashboard without any measures/dimensions.

**Expected behavior**
Rather than showing a broken dashboard, we should have a CTA that tells the user the problem.
