### ISSUE TITLE
Dashboard: an `include` access policy breaks the dashboard

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3835]
The following access policy breaks the dashboard.
```yaml
security:
  access: "{{ .user.admin }} OR '{{ .user.domain }}' == 'rilldata.com'"
  include:
    - if: "{{ .user.admin }}"
      names: 
        - total_records
        - publisher
```

In Rill Developer, use the "View As" functionality to select an admin, then see the following errors in the browser console:

![image](https://github.com/rilldata/rill/assets/14206386/55e66355-412f-4782-81fc-a8c22ca25d0a)
