### ISSUE TITLE
Ability to support the `limit` source property

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#4260]
**Is your feature request related to a problem? Please describe.**
Rather than having to define an intermediary model where we manually prescribe a limit, we should allow users / customers to directly use a `limit` source property to apply a limit on the size of the source data (for local development). 

For example, at the moment, you may need to do something like (in the model definition):
```sql
select * from table {{ if dev }} limit 1000 {{ end }}
```
However, users may be interested in defining a source YAML syntax like:
```yaml
env:
   dev: 
      limit: 1000
```

This would also allow project wide defaults to be configured in `rill.yaml` (useful when working with many potentially large datasources and enable a more frictionless local development experience). Something like:
```yaml
env:
   dev: 
      sources:
         limit: 1000
   prod:
      sources:
         refresh: `<cron>`
      models:
         materialize: true
```

Additional context from customer in Slack: https://rilldata.slack.com/archives/C05693FLY7Q/p1709743423278999?thread_ts=1709680452.047689&cid=C05693FLY7Q
