### ISSUE TITLE
web: add ability to use LIKE 'x%' instead of LIKE '%x%' for suggestiongs

### ISSUE THREAD

**Issue by azat** [rilldata/rill#5082]
Right now all completion is implemented with `LIKE '%x%'` (well, `ILIKE` to be precise), but this does not allows to use indexes (I'm talking in context of ClickHouse) so it will be good to have an option to switch to startsWith filter, so that the comletion will works way more faster.

**Comment by mindspank** [comment]
@AdityaHegde as I think you are looking at ClickHouse search?

**Comment by mindspank** [comment]
@azat Thanks for the report! Would you expect that to be the default behaviour or would you like to be able to toggle between search behaviour with a property on the dimension?

Some psuedo
```
dimensions:
  - column: country
     label: Country
     name: my_dim_id
     search: full_wild / start_wild / end_wild / exact
```
