### ISSUE TITLE
Security policy without measures should not fire certain API requests

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5224]
If you create a security policy that only includes dimension fields, but not any measure fields, it:
1. Makes a `/timeseries` request, which fails because there are no measure names
2. Makes `/aggregation` requests with an empty sort key
3. Makes a request for `/resource?name.kind=rill.runtime.v1.ProjectParser&name.name=parser`, which fails because restricted users don’t have access to parse errors

```
security:
  access: true
  include:
    - if: true
      names: [company, plan_name]
```

![Screenshot 2024-07-08 at 18 45 24](https://github.com/rilldata/rill/assets/14206386/7f64a2b1-e12f-4288-af48-701321510c98)

**Comment by lovincyrus** [comment]
Could you record a repro for me to get to the screenshot state? @ericpgreen2 

After adding the codeblock to `rill.yaml`
```
security:
  access: true
  include:
    - if: true
      names: [company, plan_name]
```

I can't seem to view the error requests as mentioned in the screenshot.. Here's what I have 

https://github.com/user-attachments/assets/2b6af5bb-5972-4b0c-897c-357c693e24dd

**Comment by ericpgreen2** [comment]
Yeah, the key is adding the codeblock to the metrics view, not `rill.yaml`. Here's one way to reproduce:
1. Clone our [example partner-filtered-dashboard project](https://github.com/rilldata/rill-examples/tree/main/rill-partner-filtered-dashboards)
2. Replace the security policy of the first dashboard (`a_admin_access.yaml`) with the above code snippet. Here's the edited file in full:
    ```yaml
    # a_admin_access.yaml
    # Visit https://docs.rilldata.com/reference/project-files to learn more about Rill project files.
    
    title: Admin-level access
    type: metrics_view
    model: margins_model
    timeseries: __time
    measures:
      - name: total_cost
        label: "Total Cost"
        expression: "SUM(cost)"
        description: "The sum of cost"
        format_preset: currency_usd
      - name: total_revenue
        label: Total Revenue
        expression: SUM(revenue)
        description: The sum of revenue
        format_preset: currency_usd
      - name: net_revenue
        label: "Net Revenue"
        expression: "SUM(revenue) - SUM(cost)"
        description: "The sum of revenue minus the sum of cost"
        format_preset: currency_usd
      - name: margin
        label: "Margin"
        expression: "(SUM(revenue) - SUM(cost))/SUM(revenue)"
        description: "Net revenue divided by sum of revenue"
        format_preset: percentage
      - name: unique_customers
        label: "Unique Customers"
        expression: "COUNT(DISTINCT company)"
        description: "The count of unique companies"
        format_preset: humanize
    dimensions:
      - name: company
        expression: company
        label: Company
        description: "The name of the company"
      - name: plan_name
        expression: plan_name
        label: Plan Name
        description: "The name of the billing plan"
      - name: location
        expression: "location"
        label: "Cost by Region"
        description: "The region incurring costs"
      - name: component
        expression: component
        label: Cost by Component
        description: "The component generating costs"
      - name: app_name
        expression: "app_name"
        label: "Cost by App Name"
        description: "The app generating costs"
      - name: sku_description
        expression: "sku_description"
        label: "Cost by SKU"
        description: "The sku description for costs"
      - name: pipeline
        expression: "pipeline"
        label: "Cost by Data Pipeline"
        description: "The pipeline incurring costs"
      - name: environment
        expression: "environment"
        label: "Cost by Environment"
        description: "The environment incurring costs"
    available_time_zones:
      - America/Los_Angeles
      - America/Chicago
      - America/New_York
    security:
      access: true
      include:
        - if: true
          names: [company, plan_name]
    ```
3. Preview the dashboard, and "View as" `admin@rilldata.com`
4. Observe the broken state
    <img width="1917" alt="image" src="https://github.com/user-attachments/assets/6a31450c-b6bd-42dc-bebc-c4deb4c6c6e6">
