### ISSUE TITLE
ClickHouse: Dashboards based on the `readonly` ClickHouse Playground don't work

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5279]
Here's my ClickHouse connector YAML:

```yaml
# clickhouse_playground.yaml
type: connector

driver: clickhouse
host: "play.clickhouse.com"
port: 443
username: play
ssl: true
settings_override: readonly=1 # Am I using this as intended?
```

I've created the following dashboard:
```yaml
# hackernews_dashboard.yaml
type: metrics_view

title: Hackernews
connector: clickhouse_playground
table: hackernews

timeseries: time

dimensions:
  - label: Type
    column: type
  - label: By
    column: by
  - label: Text
    column: text
  - label: Url
    column: url
  - label: Title
    column: title

measures:
  - name: total_records
    label: Total records
    expression: COUNT(*)
    format_preset: humanize
    valid_percent_of_total: true
```

The dashboard is blank with the following error: "clickhouse [execute]:: 500 code: Code: 164. DB::Exception: Cannot modify 'max_execution_time' setting in readonly mode. (READONLY) (version 24.6.1.2672 (official build))\n"

<img width="1914" alt="image" src="https://github.com/user-attachments/assets/de8d4bd3-1a73-47d3-af5c-10e260ad54ca">
