### ISSUE TITLE
Date dimension can no longer be used both in timeseries and specified as dimension

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#5387]
**Describe the bug**
In earlier versions of Rill, it was possible to specify a date dimension both in the `timeseries` property and as a standalone dimension within the dashboard YAML. However, that will now throw a `found duplicate dimension or measure name` error.

**Steps to reproduce**
1. Create a dashboard against a model
2. Using an existing date dimension, add it to both the `dimensions` and `timeseries` property

_Expected behavior_: Date dimension can be specified both in the timeseries and as a standalone dimension (with the same name)
_Actual behavior_: Date dimension cannot be specified with an error that there are duplicate dimension names.

<img width="1689" alt="v0 43" src="https://github.com/user-attachments/assets/006be9d8-fd84-467b-a7c9-3ba20a370b02">
<img width="1688" alt="v0 47 5 dimension timeseries" src="https://github.com/user-attachments/assets/3b2a2de8-4ef0-4de8-a128-78390990b8fb">

**Comment by k-anshul** [comment]
1. The time-dimension is considered as a dimension.
2. The restriction of having unique dimension names is indispensable.
3. The issue arises because in absence of dimension names previously the names were set as `dimension_x` and now set as column name. This can be fixed by setting name property on the dimension. Sample spec 
```
title: "Programmatic Ads Auction"
model: "auction_data_model"
type: metrics_view
timeseries: "__time"
dimensions:
  - label: time
    column: __time
    name: timed -- NEED TO SET A NAME
```
