### ISSUE TITLE
Numeric columns are converted to varchar upon import from PostgresQL

### ISSUE THREAD

**Issue by nvennin** [rilldata/rill#6186]
**Describe the bug**
When importing a view from a postgres database (hosted with supabase), columns that are fixed precision digits (numeric) are imported as varchar. I would expect them to be imported as duckdb numeric type. 

**To Reproduce**
1. Go to Sources
2. Create a model that pulls from a postgres database, containing numeric columns (see example below)

```yaml
# Source YAML
# Reference documentation: https://docs.rilldata.com/reference/project-files/sources

type: source

connector: "postgres"
database_url: "postgresql://xxxxxx@aws-0-eu-west-2.pooler.supabase.com:5432/postgres"
sql: "select line_amount_eur::real as value_real, line_amount_eur::numeric as value_numeric from analysis.sales_order_lines sol limit 10;"
```

3. See that the column casted as numeric in the sql is imported as varchar.

![image](https://github.com/user-attachments/assets/3eed1fa4-f0ec-4be0-9fb9-ca03cbe00599)

**Expected behavior**
I would expect numeric columns to be imported as numeric.

**Screenshots**
See above

**Desktop (please complete the following information):** not relevant

Rill version: 0.49.1 

**Additional context**
n/a
