### ISSUE TITLE
Advanced Measures (windowed measures, etc.) do not sure correct TDD

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#6512]
**Describe the bug**
When creating advanced window measures in a clickhouse backed project, the TDD is not selectable and shows 'no data' but the graph is correct. 

**To Reproduce**
1. Create an advanced measure, 
2. Preview in dashboard or preview mode
3. See screenshot

**Expected behavior**
```
 - name: total_customers
    expression: SUM(total_organization_id)
    requires: [total_organization_id]
    window:
      order: event_datetime
      frame: ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
```

Advanced measures should show up correctly.

**Screenshots**

![Image](https://github.com/user-attachments/assets/894f1190-0e26-4c93-adfc-453d779db378)

https://github.com/rilldata/consolidated-internal-project

**Desktop (please complete the following information):**

**Additional context**
