### ISSUE TITLE
explore access should be > than metrics layer

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#6559]
**Describe the bug**
If metrics layer is:
```
security:
  access: true
  row_filter: > 
        customer_domain = '{{ .user.domain }}' or {{ .user.admin }} 
  exclude:
    - if: "'{{.user.domain}}' != 'rilldata.com'"
      names:
        - transaction_id
        - sales_rep_email
        - sales_rep_domain
        - sales_team
        - internal_flag
        - sensitive_flag

```

and explore is 
```
security:
  access: "{{ .user.admin }} OR '{{ .user.domain }}' == 'rilldata.com'"
```

I would expect that explore dashboard would take the higher level of permissions and remove the dashboard however, that is not the case. 

**To Reproduce**
1. Set up metrics and explore as above
2. Test with a user that is not admin or rilldata.com 
3. see that metrics view gets applied

**Expected behavior**
The explore should be restricted on the access policy for dashboard. 
Use case is that im using the same metrics in a demo project to demonstrate metrics level permissions and explore and found that even setting explore level access is ignored. Will create unique metrics and explore as a workaround

**Screenshots**
![Image](https://github.com/user-attachments/assets/ab96191f-b73d-445c-813f-7dede6021909)
